lblApplicationHeader: subheader-title
lnkApplication: mp_application
btnEditPersonalInfo: mp_personal_information_edit
ddClientType: select2-realType-container
ddSelectClientType: realType
txtFirstName: mp_personal_information_firstname
txtLastName: mp_personal_information_lastname
txtJAFirstName: mp_personal_information_jointfirstname
txtJALastName: mp_personal_information_jointlastname
ddJACountryOfResidence: select2-jointCountry-container
ddSelectJACountryOfResidence: jointCountry
txtJADateOfBirth: mp_personal_information_jointdateofbirth
ddCountryOfResidence: select2-country-container
ddSelectCountryOfResidence: country
dpDateOfBirth: mp_personal_information_dateofbirth
txtMobileNumber: mp_personal_information_mobile
btnSendOtp: mp_personal_information_send_otp
txtOtp: otp-input-otpField-0
ddExpectedDeposit: select2-expectedFirstDeposit-container
ddSelectExpectedDeposit: expectedFirstDeposit
ddExpectedClientDeposit: select2-expectedClientDeposit-container
ddSelectExpectedClientDeposit: expectedClientDeposit
ddExpectedNoOfClients: select2-expectedNumberOfClients-container
ddSelectExpectedNoOfClients: expectedNumberOfClients
txtCorporateName: mp_personal_information_corporatename
txtLegalEntityIdentifier: mp_personal_information_legal_entity_identifier
lblProcessing: mp_please_wait
btnPINext: mp_personal_information_submit
btnMexAtlantic: //*[@id="trading_account_settings_regulatedEntity"]/div/label
btnMexExchange: trading_account_settings_regulatedEntity_1
btnMexPacific: trading_account_settings_regulatedEntity_2
btnMexSingapore: trading_account_settings_regulatedEntity_3
btnMt4: trading_account_settings_platformVersion_0
btnMt5: trading_account_settings_platformVersion_1
btnCTrader: img[alt='C-Trader']
btnStandard: img[alt='maximus']
btnPro: trading_account_settings_accountTier_1
btnEcn: trading_account_settings_accountTier_2
btnMexSports: trading_account_settings_accountTier_3
btnNextTradingAccount: trading_account_settings_submit
ddDefaultLeverage: select2-trading_account_settings_defaultLeverage-container
ddSelectDefaultLeverage: trading_account_settings_defaultLeverage
ddBaseCurrency: select2-trading_account_settings_baseCurrency-container
ddSelectBaseCurrency: trading_account_settings_baseCurrency
ddEmploymentInformation: select2-trading_account_settings_employmentInformation-container
ddSelectEmploymentInformation: trading_account_settings_employmentInformation
ddSourceOfFunds: select2-trading_account_settings_sourceOfFunds-container
ddSelectSourceOfFunds: trading_account_settings_sourceOfFunds
txtTaxIdentificationNumber: trading_account_settings_taxIdentificationNumber
asq1: mp_tca_selectall
selectForex: mp_tca_answer0
selectMetals: mp_tca_answer1
selectCFDs: mp_tca_answer2
selectShares: mp_tca_answer3
selectComodities: mp_tca_answer4
selectIndices: mp_tca_answer5
selectCryptocurrencies: mp_tca_answer6
selectNone: mp_tca_answer7
asq2: question-1-answer-0
falseRb1: question-1-answer-1
asq3: question-2-answer-0
falseRb2: question-2-answer-1
asq4: question-3-answer-0
falseRb3: question-3-answer-1
asq5: question-4-answer-0
falseRb4: question-4-answer-1
ddPickACountry: select2-proofOfIdentityCountries-container
ddSelectPickACountry: proofOfIdentityCountries
ddIdentityType: select2-documentTypeSelect-container
ddSelectIdentityType: documentTypeSelect
ddPassport: select2-documentTypeSelect-result-u4gc-Passport
ddResidencePermit: select2-documentTypeSelect-result-5neg-ResidencePermit
btnProofOfIdentityUpload1: //*[@id="step-5"]/div[2]/div/div[2]/div[3]/div[1]/div/div/div[1]/div[2]/button
btnProofOfIdentityUpload2: //*[@id="step-5"]/div[2]/div/div[2]/div[3]/div[2]/div/div/div[1]/div[2]/button
btnProofOfIdentity: (//*[@id="submit"])[3]
btnUtilityBillUpload: //*[@id="step-6"]/div[2]/div[1]/div/div[1]/div/div/div[1]/div[2]/button
btnOk: mp_confirm_btn
btnFinish: mp_proofofaddress_finish
lblIbSuccessMes: .card-body.p-5.px-8.text-center
btnNext: mp_tca_submit
lblUsername: mp_logged_in_user
lnkPersonalInformation: mp_personal_information
lblFirstName: real_profile_edit_firstName
lblLastName: real_profile_edit_lastName
lblEmailAddress: real_profile_edit_PortalUser
lblMobileNumber: real_profile_edit_mobileNumber
lblCountry: real_profile_edit_country
lblDateOfBirth: real_profile_edit_dateOfBirth
lnkUploadedDocuments: mp_uploaded_documents
lnkChangeEmail: mp_change_email
lnkChangeMobileNumber: mp_change_mobile_number
lnkResetPassword: mp_reset_password
lnkChangeAccountPassword: mp_change_account_password
lnkLogout: mp_logout
cbOtp: otp_checkbox_otpField

# Error Mes Locators
txtVerificationError: swal2-html-container
btnVerificationErrorOk: /html/body/div[8]/div/div[3]/button[1]
lblVerifyOtpMes: otp-message
lblFirstNameError: firstName-error
lblLastNameError: lastName-error
lblDateOfBirthError: dateOfBirth-error
lblMobileNumberError: mobileNumber-error
lblOtpError: d-block text-danger